#pragma once

#define MAINWINDOWWIDTHRATE 0.6f
#define MAINWINDOWHEIGHTRATE 0.7f
#define HIERARCHYWIDTHRATE 0.2f
#define HIERARCHYHEIGHTRATE MAINWINDOWHEIGHTRATE
#define COMPONENTWIDTHRATE 0.2f
#define COMPONENTHEIGHTRATE MAINWINDOWHEIGHTRATE
